# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi.yaml:
  no-empty-servers:
    - '#/'
  spec:
    - '#/info/servers'
    - '#/info/tags'
  info-description:
    - '#/info/description'
  no-enum-type-mismatch:
    - '#/components/schemas/BulkSMSMessageType/enum/0'
    - '#/components/schemas/BulkSMSMessageType/enum/1'
    - '#/components/schemas/BulkSMSMessageType/enum/2'
    - '#/components/schemas/BulkSMSRequestType/enum/0'
    - '#/components/schemas/BulkSMSRequestType/enum/1'
    - '#/components/schemas/BulkSMSRequestType/enum/2'
  path-parameters-defined:
    - '#/paths/~1outbox~1create{message_ref}/get/parameters'
